[tool.poetry]
name = "MoUSE-GUI"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
appdirs = "1.4.4"
argon2-cffi-bindings = "21.2.0"
asttokens = "2.4.1"
async-timeout = "4.0.3"
attrs = "23.2.0"
audioread = "3.0.1"
backcall = "0.2.0"
bayesian-optimization = "1.4.3"
beautifulsoup4 = "4.12.3"
bleach = "6.1.0"
bs4 = "0.0.2"
cachetools = "5.3.3"
certifi = "2024.2.2"
cffi = "1.16.0"
charset-normalizer = "2.1.1"
click = "8.1.7"
cloudpickle = "3.0.0"
commonmark = "0.9.1"
cycler = "0.12.1"
Cython = "3.0.10"
debugpy = "1.8.1"
decorator = "5.1.1"
deepdish = "0.3.7"
defusedxml = "0.7.1"
Deprecated = "1.2.14"
dm-tree = "0.1.8"
entrypoints = "0.4"
environ-config = "23.2.0"
executing = "2.0.1"
fastjsonschema = "2.19.1"
filelock = "3.13.4"
fonttools = "4.51.0"
frozenlist = "1.4.1"
fsspec = "2024.3.1"
future = "1.0.0"
gdown = "5.1.0"
google-auth = "2.29.0"
google-auth-oauthlib = "1.2.0"
grpcio = "1.62.1"
gym = "0.26.2"
idna = "3.7"
imageio = "2.34.0"
importlib-resources = "6.4.0"
iniconfig = "2.0.0"
ipykernel = "6.29.4"
ipython = "8.23.0"
ipython-genutils = "0.2.0"
ipywidgets = "8.1.2"
jedi = "0.19.1"
Jinja2 = "3.1.3"
joblib = "1.4.0"
jsonschema = "4.21.1"
kiwisolver = "1.4.5"
librosa = "0.10.1"
llvmlite = "0.42.0"
lz4 = "4.3.3"
Markdown = "3.6"
MarkupSafe = "2.1.5"
matplotlib = "3.8.4"
matplotlib-inline = "0.1.6"
mccabe = "0.7.0"
mistune = "3.0.2"
MoUSE = { git = "https://github.com/JosephTheMoUSE/MoUSE.git", branch = "python3.11-adjustment" }
msgpack = "1.0.8"
multidict = "6.0.5"
mypy = "1.9.0"
mypy-extensions = "1.0.0"
nbclient = "0.10.0"
nbconvert = "7.16.3"
nbformat = "5.10.4"
nest-asyncio = "1.6.0"
networkx = "3.3"
numba = "0.59.1"
numexpr = "2.10.0"
numpy = "1.26.4"
oauthlib = "3.2.2"
opencv-python = "4.9.0.80"
packaging = "24.0"
pandas = "2.2.2"
pandocfilters = "1.5.1"
parso = "0.8.4"
pathspec = "0.12.1"
pexpect = "4.9.0"
pickleshare = "0.7.5"
Pillow = "10.3.0"
pip-search = "0.0.12"
platformdirs = "4.2.0"
pluggy = "1.5.0"
pooch = "1.8.1"
prometheus-client = "0.20.0"
prompt-toolkit = "3.0.43"
protobuf3 = "0.2.1"
psutil = "5.9.8"
ptyprocess = "0.7.0"
pure-eval = "0.2.2"
py = "1.11.0"
pyasn1 = "0.6.0"
pyasn1-modules = "0.4.0"
pycodestyle = "2.11.1"
pycparser = "2.22"
pyDeprecate = "0.3.2"
pydeps = "1.12.20"
pydocstyle = "6.3.0"
pyflakes = "3.2.0"
Pygments = "2.17.2"
pyparsing = "3.1.2"
pyrsistent = "0.20.0"
PySide6 = "6.7.0"
PySocks = "1.7.1"
pytest = "8.2.0"
pytest-qt = "4.4.0"
python-dateutil = "2.9.0.post0"
pytorch-lightning = "2.2.2"
pytz = "2024.1"
PyWavelets = "1.6.0"
PyYAML = "6.0.1"
pyzmq = "25.1.2"
qtconsole = "5.5.1"
QtPy = "2.4.1"
ray = { version = "2.10.0", extras = ["tune"] }
redis = "5.0.3"
requests = "2.31.0"
requests-oauthlib = "2.0.0"
resampy = "0.4.3"
rich = "13.7.1"
rsa = "4.9"
Rtree = "1.2.0"
scikit-image = "0.23.1"
scikit-learn = "1.4.2"
scipy = "1.13.0"
Send2Trash = "1.8.3"
setuptools-scm = "8.0.4"
setproctitle = "1.3.3"
shiboken6 = "6.7.0"
six = "1.16.0"
snowballstemmer = "2.2.0"
SoundFile = "0.12.1"
soupsieve = "2.5"
stack-data = "0.6.3"
stdlib-list = "0.10.0"
tables = "3.9.2"
tabulate = "0.9.0"
tensorboard = "2.16.2"
tensorboard-data-server = "0.7.2"
tensorboard-plugin-wit = "1.8.1"
tensorboardX = "2.6.2.2"
terminado = "0.18.1"
threadpoolctl = "3.4.0"
tifffile = "2024.2.12"
tinycss2 = "1.2.1"
toml = "0.10.2"
tomli = "2.0.1"
torch = "2.2.2"
torchaudio = "2.2.2"
torchmetrics = "1.3.2"
torchvision = "0.17.2"
tornado = "6.4"
tqdm = "4.66.2"
traitlets = "5.14.2"
typing-extensions = "4.11.0"
urllib3 = "2.2.1"
wcwidth = "0.2.13"
webencodings = "0.5.1"
Werkzeug = "3.0.2"
widgetsnbextension = "4.0.10"
wrapt = "1.16.0"
yarl = "1.9.4"
zipp = "3.18.1"

[tool.poetry.group.dev.dependencies]
deptry = "^0.16.1"

[tool.flake8]
docstring-convention = "numpy"
ignore = ["W", "E", "F", "D100", "D101", "D102", "D103", "D104", "D105"]
exclude = [
    "./src/mouseapp/view/generated",
    "./experimental/"
]

[tool.yapf]
based_on_style = "google"
split_all_top_level_comma_separated_values = true
column_limit = 88

[tool.poetry.dev-dependencies]
flake8 = "7.0.0"
yapf = "0.40.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"